language: node_js
node_js:
  - 8.4
before_install:
  - "npm i -g bower karma-cli"
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
after_script:
  - ls ./coverage
  - 'npm install coveralls@2.10.0 && cat "./coverage/Firefox 31.0.0 (Linux)/lcov.info" | coveralls'
